version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

    volumes:
      - ./library_back/postgres:/var/lib/postgres
      - ./library_back/postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
    
    networks:
      - network-api
  
  back:
    build: ./library_back
    ports:
      - 8000:8000

    volumes:
      - ./library_back:/library_back

    depends_on:
      - db

    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    
    networks:
      - network-api

networks:
  network-api:
    driver: bridge