version: '3.8'

services:
  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432

    volumes:
      - ./library_back/postgres:/var/lib/postgres
    
    networks:
      - network-api
  
  back:
    build: ./library_back
    ports:
      - 8000:8000

    volumes:
      - ./library_back:/library_back

    depends_on:
      - db

    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    
    networks:
      - network-api

  front:
    build: ./library_front
    
    ports:
      - 3000:3000

    depends_on:
      - back
    
    volumes:
      - ./library_front:/library_front

    networks:
      - network-api
  
  nginx:
    image: nginx
    
    container_name: nginx

    restart: always

    ports:
      - 80:80

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
    depends_on:
      - front

    networks:
      - network-api


networks:
  network-api:
    driver: bridge